/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/model/building2.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/building2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.001']} position={[-0.014, -0.168, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.001']} position={[-0.014, -0.168, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.001']} position={[-0.014, -0.168, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.001']} position={[-0.014, 0.187, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.001']} position={[-0.014, 0.533, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.001']} position={[-0.014, 0.533, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials['Material.001']} position={[-0.014, 0.533, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.001']} position={[-0.014, 0.888, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials['Material.001']} position={[-0.014, 1.245, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials['Material.001']} position={[-0.014, 1.245, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['Material.001']} position={[-0.014, 1.245, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials['Material.001']} position={[-0.014, 1.6, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube013.geometry} material={materials['Material.001']} position={[-0.014, 1.946, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube014.geometry} material={materials['Material.001']} position={[-0.014, 1.946, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube015.geometry} material={materials['Material.001']} position={[-0.014, 1.946, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube016.geometry} material={materials['Material.001']} position={[-0.014, 2.301, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube017.geometry} material={materials['Material.001']} position={[-0.014, 2.639, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube018.geometry} material={materials['Material.001']} position={[-0.014, 2.639, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube019.geometry} material={materials['Material.001']} position={[-0.014, 2.639, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube020.geometry} material={materials['Material.001']} position={[-0.014, 2.994, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube021.geometry} material={materials['Material.001']} position={[-0.014, 3.34, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube022.geometry} material={materials['Material.001']} position={[-0.014, 3.34, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube023.geometry} material={materials['Material.001']} position={[-0.014, 3.34, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube024.geometry} material={materials['Material.001']} position={[-0.014, 3.695, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube025.geometry} material={materials['Material.001']} position={[-0.014, 4.052, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube026.geometry} material={materials['Material.001']} position={[-0.014, 4.052, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube027.geometry} material={materials['Material.001']} position={[-0.014, 4.052, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube028.geometry} material={materials['Material.001']} position={[-0.014, 4.407, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube029.geometry} material={materials['Material.001']} position={[-0.014, 4.753, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube030.geometry} material={materials['Material.001']} position={[-0.014, 4.753, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube031.geometry} material={materials['Material.001']} position={[-0.014, 4.753, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube032.geometry} material={materials['Material.001']} position={[-0.014, 5.108, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube033.geometry} material={materials['Material.001']} position={[-0.014, 5.416, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube034.geometry} material={materials['Material.001']} position={[-0.014, 5.773, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube035.geometry} material={materials['Material.001']} position={[-0.014, 5.773, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube036.geometry} material={materials['Material.001']} position={[-0.014, 5.773, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube037.geometry} material={materials['Material.001']} position={[-0.014, 6.128, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube038.geometry} material={materials['Material.001']} position={[-0.014, 6.474, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube039.geometry} material={materials['Material.001']} position={[-0.014, 6.474, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube040.geometry} material={materials['Material.001']} position={[-0.014, 6.474, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
      <mesh geometry={nodes.Cube041.geometry} material={materials['Material.001']} position={[-0.014, 6.829, -0.008]} rotation={[-Math.PI, 0, 0]} scale={[-1.359, -0.178, -2.016]} />
    </group>
  )
}

useGLTF.preload('/building2.glb')
