/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/model/untitled.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/untitled.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[1058.581, 1814.948, 594.273]}>
          <mesh geometry={nodes.Box001_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[182.432, -613.289, -694.012]} />
        </group>
        <group position={[1058.581, 1514.584, 594.273]}>
          <mesh geometry={nodes.Box002_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[182.432, -613.289, -694.012]} />
        </group>
        <group position={[1058.581, 1214.777, 594.273]}>
          <mesh geometry={nodes.Box003_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[182.432, -613.289, -694.012]} />
        </group>
        <group position={[1058.581, 913.662, 594.273]}>
          <mesh geometry={nodes.Box004_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[182.432, -613.289, -694.012]} />
        </group>
        <group position={[-1202.423, 313.858, 97.936]}>
          <mesh geometry={nodes.Box013_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[182.432, -613.289, -694.012]} />
        </group>
        <group position={[-1202.423, 614.561, 97.936]}>
          <mesh geometry={nodes.Box014_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[182.432, -613.289, -694.012]} />
        </group>
        <group position={[-1202.423, 913.919, 97.936]}>
          <mesh geometry={nodes.Box015_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[182.432, -613.289, -694.012]} />
        </group>
        <group position={[-1202.423, 1214.521, 97.936]}>
          <mesh geometry={nodes.Box016_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[182.432, -613.289, -694.012]} />
        </group>
        <group position={[-1202.423, 1515.16, 97.936]}>
          <mesh geometry={nodes.Box017_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[182.432, -613.289, -694.012]} />
        </group>
        <group position={[-1202.423, 1814.447, 97.936]}>
          <mesh geometry={nodes.Box018_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[182.432, -613.289, -694.012]} />
        </group>
        <group position={[-1202.423, 2115.075, 97.936]}>
          <mesh geometry={nodes.Box019_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[182.432, -613.289, -694.012]} />
        </group>
        <group position={[-1202.423, 2416.63, 97.936]}>
          <mesh geometry={nodes.Box020_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[182.432, -613.289, -694.012]} />
        </group>
        <group position={[-1202.423, 313.858, 371.069]} rotation={[0, 0, -Math.PI]} scale={-1}>
          <mesh geometry={nodes.Box023_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[182.432, -613.289, -694.012]} />
        </group>
        <group position={[-1202.423, 614.561, 371.069]} rotation={[0, 0, -Math.PI]} scale={-1}>
          <mesh geometry={nodes.Box024_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[182.432, -613.289, -694.012]} />
        </group>
        <group position={[-1202.423, 913.919, 371.069]} rotation={[0, 0, -Math.PI]} scale={-1}>
          <mesh geometry={nodes.Box025_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[182.432, -613.289, -694.012]} />
        </group>
        <group position={[-1202.423, 1214.521, 371.069]} rotation={[0, 0, -Math.PI]} scale={-1}>
          <mesh geometry={nodes.Box026_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[182.432, -613.289, -694.012]} />
        </group>
        <group position={[-1202.423, 1515.16, 371.069]} rotation={[0, 0, -Math.PI]} scale={-1}>
          <mesh geometry={nodes.Box027_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[182.432, -613.289, -694.012]} />
        </group>
        <group position={[-1202.423, 1814.447, 371.069]} rotation={[0, 0, -Math.PI]} scale={-1}>
          <mesh geometry={nodes.Box028_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[182.432, -613.289, -694.012]} />
        </group>
        <group position={[-1202.423, 2115.075, 371.069]} rotation={[0, 0, -Math.PI]} scale={-1}>
          <mesh geometry={nodes.Box029_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[182.432, -613.289, -694.012]} />
        </group>
        <group position={[-1202.423, 2416.63, 371.069]} rotation={[0, 0, -Math.PI]} scale={-1}>
          <mesh geometry={nodes.Box030_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[182.432, -613.289, -694.012]} />
        </group>
        <group position={[-225.308, 1200, -147.129]} rotation={[-Math.PI / 2, 0, Math.PI]}>
          <mesh geometry={nodes['Line001_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[400.475, 259.233, -1200]} />
        </group>
        <group position={[-225.308, 14.989, -147.129]} rotation={[-Math.PI / 2, 0, Math.PI]}>
          <mesh geometry={nodes.Shape001_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[400.475, 259.233, -2415]} />
        </group>
        <group position={[-225.308, 314.989, -147.129]} rotation={[-Math.PI / 2, 0, Math.PI]}>
          <mesh geometry={nodes.Shape002_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[400.475, 259.233, -2415]} />
        </group>
        <group position={[-225.308, 614.989, -147.129]} rotation={[-Math.PI / 2, 0, Math.PI]}>
          <mesh geometry={nodes.Shape003_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[400.475, 259.233, -2415]} />
        </group>
        <group position={[-225.308, 914.989, -147.129]} rotation={[-Math.PI / 2, 0, Math.PI]}>
          <mesh geometry={nodes.Shape004_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[400.475, 259.233, -2415]} />
        </group>
        <group position={[-225.308, 1214.989, -147.129]} rotation={[-Math.PI / 2, 0, Math.PI]}>
          <mesh geometry={nodes.Shape005_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[400.475, 259.233, -2415]} />
        </group>
        <group position={[-225.308, 1514.989, -147.129]} rotation={[-Math.PI / 2, 0, Math.PI]}>
          <mesh geometry={nodes.Shape006_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[400.475, 259.233, -2415]} />
        </group>
        <group position={[-225.308, 1814.989, -147.129]} rotation={[-Math.PI / 2, 0, Math.PI]}>
          <mesh geometry={nodes.Shape007_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[400.475, 259.233, -2415]} />
        </group>
        <group position={[-225.308, 2114.989, -147.129]} rotation={[-Math.PI / 2, 0, Math.PI]}>
          <mesh geometry={nodes.Shape008_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[400.475, 259.233, -2415]} />
        </group>
        <group position={[-225.308, 2414.989, -147.129]} rotation={[-Math.PI / 2, 0, Math.PI]}>
          <mesh geometry={nodes.Shape009_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[400.475, 259.233, -2415]} />
        </group>
        <mesh geometry={nodes['Box005_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[508.069, 1280.405, 1125.747]} />
        <mesh geometry={nodes['Box006_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[1117.358, 1280.405, -289.928]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes['Box007_04_-_Default_0'].geometry} material={materials['04_-_Default']} position={[1401.534, 1280.405, 1125.609]} />
        <mesh geometry={nodes['Box008_04_-_Default_0'].geometry} material={materials['04_-_Default']} position={[600.3, 1861.396, 925.47]} />
        <mesh geometry={nodes['Box009_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[115.931, 1280.405, 853.86]} />
        <mesh geometry={nodes['Box010_03_-_Default_0'].geometry} material={materials['03_-_Default']} position={[115.931, 545.677, 853.86]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes['Box011_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[-1652.795, 1280.405, 569.414]} />
        <mesh geometry={nodes['Box012_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[-1241.197, 1280.405, 569.414]} />
        <mesh geometry={nodes['Box021_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[-1652.795, 1280.405, -85.822]} rotation={[0, 0, -Math.PI]} scale={-1} />
        <mesh geometry={nodes['Box022_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[-1241.197, 1280.405, -85.822]} rotation={[0, 0, -Math.PI]} scale={-1} />
        <mesh geometry={nodes['Box031_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[870.373, 1280.405, -779.694]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes['Box032_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[870.373, 1280.405, -869.199]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes['Box033_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[870.373, 1280.405, -1309.605]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes['Box034_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[-720.288, 1280.405, -779.694]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes['Box035_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[-720.288, 1280.405, -869.199]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes['Box036_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[-720.288, 1280.405, -1309.605]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes['Box037_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[870.373, 2192.504, -979.19]} rotation={[Math.PI, 0, Math.PI / 2]} />
        <mesh geometry={nodes['Box038_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[870.373, 1893.345, -979.19]} rotation={[Math.PI, 0, Math.PI / 2]} />
        <mesh geometry={nodes['Box039_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[870.373, 1589.486, -979.19]} rotation={[Math.PI, 0, Math.PI / 2]} />
        <mesh geometry={nodes['Box040_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[870.373, 1291.953, -979.19]} rotation={[Math.PI, 0, Math.PI / 2]} />
        <mesh geometry={nodes['Box041_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[870.373, 989.636, -979.19]} rotation={[Math.PI, 0, Math.PI / 2]} />
        <mesh geometry={nodes['Box042_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[870.373, 690.408, -979.19]} rotation={[Math.PI, 0, Math.PI / 2]} />
        <mesh geometry={nodes['Box043_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[870.373, 394.238, -979.19]} rotation={[Math.PI, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Box044_Ceramic_0.geometry} material={materials.Ceramic} position={[-173.541, -4.94, 67.911]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box045_05_-_Default_0'].geometry} material={materials['05_-_Default']} position={[-102.246, -74.949, 25.015]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box046_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[1482.586, 927.836, -273.61]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box047_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[1482.586, 1228.34, -273.61]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box048_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[1482.586, 1527.849, -273.61]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box049_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[1482.586, 1823.35, -273.61]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box050_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[1482.586, 927.836, 453.938]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box051_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[1482.586, 1228.34, 453.938]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box052_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[1482.586, 1527.849, 453.938]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box053_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[1482.586, 1823.35, 453.938]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box054_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[1482.586, 927.836, 1165.055]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box055_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[1482.586, 1228.34, 1165.055]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box056_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[1482.586, 1527.849, 1165.055]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box057_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[1482.586, 1823.35, 1165.055]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box058_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[1482.586, 927.836, 1484.159]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box059_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[1482.586, 1228.34, 1484.159]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box060_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[1482.586, 1527.849, 1484.159]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box061_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[1482.586, 1823.35, 1484.159]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box062_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[1099.688, 927.836, 1484.159]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box063_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[1099.688, 1228.34, 1484.159]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box064_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[1099.688, 1527.849, 1484.159]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box065_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[1099.688, 1823.35, 1484.159]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box066_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[716.791, 927.836, 1484.159]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box067_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[716.791, 1228.34, 1484.159]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box068_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[716.791, 1527.849, 1484.159]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box069_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[716.791, 1823.35, 1484.159]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box070_15_-_Glossy_Plastic_0'].geometry} material={materials['15_-_Glossy_Plastic']} position={[-1822.985, 1272.851, 185.454]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes['Box071_15_-_Glossy_Plastic_0'].geometry} material={materials['15_-_Glossy_Plastic']} position={[-994.891, 1272.851, 778.949]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh geometry={nodes['Box072_15_-_Glossy_Plastic_0'].geometry} material={materials['15_-_Glossy_Plastic']} position={[-84.457, 1272.851, 1230.822]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh geometry={nodes['Box073_15_-_Glossy_Plastic_0'].geometry} material={materials['15_-_Glossy_Plastic']} position={[1272.51, 1272.851, -203.425]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes['Box074_15_-_Glossy_Plastic_0'].geometry} material={materials['15_-_Glossy_Plastic']} position={[1185.709, 1272.851, -1438.398]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh geometry={nodes['Box075_15_-_Glossy_Plastic_0'].geometry} material={materials['15_-_Glossy_Plastic']} position={[-202.124, 1272.851, -1245.034]} rotation={[0, -1.571, 0]} />
        <mesh geometry={nodes['Box076_16_-_Matte_Plastic_0'].geometry} material={materials['16_-_Matte_Plastic']} position={[255.415, 2411.674, 481.816]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box077_16_-_Matte_Plastic_0'].geometry} material={materials['16_-_Matte_Plastic']} position={[255.415, 2411.674, -775.986]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box078_16_-_Matte_Plastic_0'].geometry} material={materials['16_-_Matte_Plastic']} position={[-1081.466, 2411.674, 219.066]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Box079_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[255.415, 2517.767, 481.816]} rotation={[-Math.PI / 2, 0, 0]} scale={1.063} />
        <mesh geometry={nodes.Box080_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[-1079.323, 2517.767, 219.117]} rotation={[-Math.PI / 2, 0, 0]} scale={1.063} />
        <mesh geometry={nodes.Box081_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[254.666, 2517.767, -778.726]} rotation={[-Math.PI / 2, 0, 0]} scale={1.063} />
        <mesh geometry={nodes['Box082_12_-_Car_Paint_0'].geometry} material={materials['12_-_Car_Paint']} position={[-1379.753, 0, 989.451]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box083_12_-_Car_Paint_0'].geometry} material={materials['12_-_Car_Paint']} position={[-1379.753, 333.838, 989.451]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box084_12_-_Car_Paint_0'].geometry} material={materials['12_-_Car_Paint']} position={[-1379.753, 637.321, 989.451]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box085_12_-_Car_Paint_0'].geometry} material={materials['12_-_Car_Paint']} position={[-1379.753, 937.653, 989.451]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box086_12_-_Car_Paint_0'].geometry} material={materials['12_-_Car_Paint']} position={[-1379.753, 1236.914, 989.451]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box087_12_-_Car_Paint_0'].geometry} material={materials['12_-_Car_Paint']} position={[-1379.753, 1539.177, 989.451]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box088_12_-_Car_Paint_0'].geometry} material={materials['12_-_Car_Paint']} position={[-1379.753, 1836.403, 989.451]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box089_12_-_Car_Paint_0'].geometry} material={materials['12_-_Car_Paint']} position={[-1379.753, 2139.027, 989.451]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box090_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[-1233.395, -3.171, 999.756]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box091_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[-1528.321, -3.171, 999.756]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box092_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[-1233.395, 321.811, 999.756]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box093_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[-1528.321, 321.811, 999.756]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box094_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[-1233.395, 628.422, 999.756]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box095_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[-1528.321, 628.422, 999.756]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box096_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[-1233.395, 925.789, 999.756]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box097_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[-1528.321, 925.789, 999.756]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box098_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[-1233.395, 1227.742, 999.756]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box099_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[-1528.321, 1227.742, 999.756]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box100_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[-1233.395, 1528.564, 999.756]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box101_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[-1528.321, 1528.564, 999.756]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box102_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[-1233.395, 1825.828, 999.756]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box103_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[-1528.321, 1825.828, 999.756]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box104_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[-1233.395, 2126.601, 999.756]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box105_13_-_Brushed_Metal_#2_0'].geometry} material={materials['13_-_Brushed_Metal_2']} position={[-1528.321, 2126.601, 999.756]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Line002_03_-_Default_0'].geometry} material={materials['03_-_Default']} position={[380.235, 255.061, 1666.072]} />
        <mesh geometry={nodes['Line003_03_-_Default_0'].geometry} material={materials['03_-_Default']} position={[380.235, 255.061, 1814.573]} />
        <mesh geometry={nodes['Line004_03_-_Default_0'].geometry} material={materials['03_-_Default']} position={[380.235, 255.061, 1963.074]} />
        <mesh geometry={nodes['Line005_03_-_Default_0'].geometry} material={materials['03_-_Default']} position={[380.235, 255.061, 2111.575]} />
        <mesh geometry={nodes.Line006__0.geometry} material={materials.Line006__0} position={[121.384, 97.887, -141.077]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Line007_Solid_Glass_0.geometry} material={materials.Solid_Glass} position={[-25.4, 0, 314.738]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Line008_06_-_Default_0'].geometry} material={materials['06_-_Default']} position={[-929.379, 0, 1590.073]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Line009_12_-_Car_Paint_0'].geometry} material={materials['12_-_Car_Paint']} position={[1202.158, 1871.09, 593.982]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Line010_12_-_Car_Paint_0'].geometry} material={materials['12_-_Car_Paint']} position={[1202.158, 1576.042, 593.982]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Line011_12_-_Car_Paint_0'].geometry} material={materials['12_-_Car_Paint']} position={[1202.158, 1276.418, 593.982]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Line012_12_-_Car_Paint_0'].geometry} material={materials['12_-_Car_Paint']} position={[1202.158, 975.391, 593.982]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Line013_14_-_Polished_Aluminum_0'].geometry} material={materials['14_-_Polished_Aluminum']} position={[-21.319, 2461.303, 104.781]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Rectangle001_Metal_0.geometry} material={materials.Metal} position={[-580.811, 2256.341, 721.928]} />
        <mesh geometry={nodes['Rectangle002_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-580.811, 2256.341, 719.762]} />
        <mesh geometry={nodes.Rectangle003_Metal_0.geometry} material={materials.Metal} position={[-580.811, 1958.82, 721.928]} />
        <mesh geometry={nodes['Rectangle004_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-580.811, 1958.82, 719.762]} />
        <mesh geometry={nodes.Rectangle005_Metal_0.geometry} material={materials.Metal} position={[-580.811, 1656.472, 721.928]} />
        <mesh geometry={nodes['Rectangle006_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-580.811, 1656.472, 719.762]} />
        <mesh geometry={nodes.Rectangle007_Metal_0.geometry} material={materials.Metal} position={[-580.811, 1357.274, 721.928]} />
        <mesh geometry={nodes['Rectangle008_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-580.811, 1357.274, 719.762]} />
        <mesh geometry={nodes.Rectangle009_Metal_0.geometry} material={materials.Metal} position={[-580.811, 1061.153, 721.928]} />
        <mesh geometry={nodes['Rectangle010_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-580.811, 1061.153, 719.762]} />
        <mesh geometry={nodes.Rectangle011_Metal_0.geometry} material={materials.Metal} position={[-580.811, 758.638, 721.928]} />
        <mesh geometry={nodes['Rectangle012_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-580.811, 758.638, 719.762]} />
        <mesh geometry={nodes.Rectangle013_Metal_0.geometry} material={materials.Metal} position={[-580.811, 458.613, 721.928]} />
        <mesh geometry={nodes['Rectangle014_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-580.811, 458.613, 719.762]} />
        <mesh geometry={nodes.Rectangle015_Metal_0.geometry} material={materials.Metal} position={[-580.811, 159.435, 721.928]} />
        <mesh geometry={nodes['Rectangle016_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-580.811, 159.435, 719.762]} />
        <mesh geometry={nodes.Rectangle017_Metal_0.geometry} material={materials.Metal} position={[-580.811, 2256.341, -294.464]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle018_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-580.811, 2256.341, -292.298]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle019_Metal_0.geometry} material={materials.Metal} position={[-580.811, 1958.82, -294.464]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle020_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-580.811, 1958.82, -292.298]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle021_Metal_0.geometry} material={materials.Metal} position={[-580.811, 1656.472, -294.464]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle022_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-580.811, 1656.472, -292.298]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle023_Metal_0.geometry} material={materials.Metal} position={[-580.811, 1357.274, -294.464]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle024_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-580.811, 1357.274, -292.298]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle025_Metal_0.geometry} material={materials.Metal} position={[-580.811, 1061.153, -294.464]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle026_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-580.811, 1061.153, -292.298]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle027_Metal_0.geometry} material={materials.Metal} position={[-580.811, 758.638, -294.464]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle028_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-580.811, 758.638, -292.298]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle029_Metal_0.geometry} material={materials.Metal} position={[-580.811, 458.613, -294.464]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle030_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-580.811, 458.613, -292.298]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle031_Metal_0.geometry} material={materials.Metal} position={[-580.811, 159.435, -294.464]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle032_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-580.811, 159.435, -292.298]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle033_Metal_0.geometry} material={materials.Metal} position={[-1378.765, 2256.341, -294.464]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle034_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-1378.765, 2256.341, -292.298]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle035_Metal_0.geometry} material={materials.Metal} position={[-1378.765, 1958.82, -294.464]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle036_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-1378.765, 1958.82, -292.298]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle037_Metal_0.geometry} material={materials.Metal} position={[-1378.765, 1656.472, -294.464]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle038_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-1378.765, 1656.472, -292.298]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle039_Metal_0.geometry} material={materials.Metal} position={[-1378.765, 1357.274, -294.464]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle040_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-1378.765, 1357.274, -292.298]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle041_Metal_0.geometry} material={materials.Metal} position={[-1378.765, 1061.153, -294.464]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle042_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-1378.765, 1061.153, -292.298]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle043_Metal_0.geometry} material={materials.Metal} position={[-1378.765, 758.638, -294.464]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle044_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-1378.765, 758.638, -292.298]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle045_Metal_0.geometry} material={materials.Metal} position={[-1378.765, 458.613, -294.464]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle046_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-1378.765, 458.613, -292.298]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle047_Metal_0.geometry} material={materials.Metal} position={[-1378.765, 159.435, -294.464]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle048_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-1378.765, 159.435, -292.298]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle049_Metal_0.geometry} material={materials.Metal} position={[-1379.471, 2256.341, 721.928]} />
        <mesh geometry={nodes['Rectangle050_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-1379.471, 2256.341, 719.762]} />
        <mesh geometry={nodes.Rectangle051_Metal_0.geometry} material={materials.Metal} position={[-1379.471, 1958.82, 721.928]} />
        <mesh geometry={nodes['Rectangle052_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-1379.471, 1958.82, 719.762]} />
        <mesh geometry={nodes.Rectangle053_Metal_0.geometry} material={materials.Metal} position={[-1379.471, 1656.472, 721.928]} />
        <mesh geometry={nodes['Rectangle054_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-1379.471, 1656.472, 719.762]} />
        <mesh geometry={nodes.Rectangle055_Metal_0.geometry} material={materials.Metal} position={[-1379.471, 1357.274, 721.928]} />
        <mesh geometry={nodes['Rectangle056_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-1379.471, 1357.274, 719.762]} />
        <mesh geometry={nodes.Rectangle057_Metal_0.geometry} material={materials.Metal} position={[-1379.471, 1061.153, 721.928]} />
        <mesh geometry={nodes['Rectangle058_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-1379.471, 1061.153, 719.762]} />
        <mesh geometry={nodes.Rectangle059_Metal_0.geometry} material={materials.Metal} position={[-1379.471, 758.638, 721.928]} />
        <mesh geometry={nodes['Rectangle060_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-1379.471, 758.638, 719.762]} />
        <mesh geometry={nodes.Rectangle061_Metal_0.geometry} material={materials.Metal} position={[-1379.471, 458.613, 721.928]} />
        <mesh geometry={nodes['Rectangle062_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-1379.471, 458.613, 719.762]} />
        <mesh geometry={nodes.Rectangle063_Metal_0.geometry} material={materials.Metal} position={[-1379.471, 159.435, 721.928]} />
        <mesh geometry={nodes['Rectangle064_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-1379.471, 159.435, 719.762]} />
        <mesh geometry={nodes.Rectangle065_Metal_0.geometry} material={materials.Metal} position={[796.454, 2256.341, -1473.243]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle066_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[796.454, 2256.341, -1471.077]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle067_Metal_0.geometry} material={materials.Metal} position={[796.454, 1958.82, -1473.243]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle068_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[796.454, 1958.82, -1471.077]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle069_Metal_0.geometry} material={materials.Metal} position={[796.454, 1656.472, -1473.243]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle070_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[796.454, 1656.472, -1471.077]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle071_Metal_0.geometry} material={materials.Metal} position={[796.454, 1357.274, -1473.243]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle072_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[796.454, 1357.274, -1471.077]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle073_Metal_0.geometry} material={materials.Metal} position={[796.454, 1061.153, -1473.243]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle074_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[796.454, 1061.153, -1471.077]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle075_Metal_0.geometry} material={materials.Metal} position={[796.454, 758.638, -1473.243]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle076_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[796.454, 758.638, -1471.077]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle077_Metal_0.geometry} material={materials.Metal} position={[796.454, 458.613, -1473.243]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle078_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[796.454, 458.613, -1471.077]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle079_Metal_0.geometry} material={materials.Metal} position={[796.454, 159.435, -1473.243]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle080_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[796.454, 159.435, -1471.077]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle081_Metal_0.geometry} material={materials.Metal} position={[397.389, 2256.341, -1473.243]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle082_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[397.389, 2256.341, -1471.077]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle083_Metal_0.geometry} material={materials.Metal} position={[397.389, 1958.82, -1473.243]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle084_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[397.389, 1958.82, -1471.077]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle085_Metal_0.geometry} material={materials.Metal} position={[397.389, 1656.472, -1473.243]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle086_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[397.389, 1656.472, -1471.077]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle087_Metal_0.geometry} material={materials.Metal} position={[397.389, 1357.274, -1473.243]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle088_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[397.389, 1357.274, -1471.077]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle089_Metal_0.geometry} material={materials.Metal} position={[397.389, 1061.153, -1473.243]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle090_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[397.389, 1061.153, -1471.077]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle091_Metal_0.geometry} material={materials.Metal} position={[397.389, 758.638, -1473.243]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle092_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[397.389, 758.638, -1471.077]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle093_Metal_0.geometry} material={materials.Metal} position={[397.389, 458.613, -1473.243]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle094_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[397.389, 458.613, -1471.077]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle095_Metal_0.geometry} material={materials.Metal} position={[397.389, 159.435, -1473.243]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle096_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[397.389, 159.435, -1471.077]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle097_Metal_0.geometry} material={materials.Metal} position={[-1.918, 2256.341, -1473.243]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle098_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-1.918, 2256.341, -1471.077]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle099_Metal_0.geometry} material={materials.Metal} position={[-1.918, 1958.82, -1473.243]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle100_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-1.918, 1958.82, -1471.077]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle101_Metal_0.geometry} material={materials.Metal} position={[-1.918, 1656.472, -1473.243]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle102_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-1.918, 1656.472, -1471.077]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle103_Metal_0.geometry} material={materials.Metal} position={[-1.918, 1357.274, -1473.243]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle104_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-1.918, 1357.274, -1471.077]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle105_Metal_0.geometry} material={materials.Metal} position={[-1.918, 1061.153, -1473.243]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle106_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-1.918, 1061.153, -1471.077]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle107_Metal_0.geometry} material={materials.Metal} position={[-1.918, 758.638, -1473.243]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle108_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-1.918, 758.638, -1471.077]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle109_Metal_0.geometry} material={materials.Metal} position={[-1.918, 458.613, -1473.243]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle110_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-1.918, 458.613, -1471.077]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle111_Metal_0.geometry} material={materials.Metal} position={[-1.918, 159.435, -1473.243]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes['Rectangle112_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-1.918, 159.435, -1471.077]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Rectangle113_Metal_0.geometry} material={materials.Metal} position={[1314.045, 2256.341, -1151.974]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle114_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[1311.879, 2256.341, -1151.974]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle115_Metal_0.geometry} material={materials.Metal} position={[1314.045, 1958.82, -1151.974]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle116_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[1311.879, 1958.82, -1151.974]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle117_Metal_0.geometry} material={materials.Metal} position={[1314.045, 1656.472, -1151.974]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle118_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[1311.879, 1656.472, -1151.974]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle119_Metal_0.geometry} material={materials.Metal} position={[1314.045, 1357.274, -1151.974]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle120_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[1311.879, 1357.274, -1151.974]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle121_Metal_0.geometry} material={materials.Metal} position={[1314.045, 1061.153, -1151.974]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle122_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[1311.879, 1061.153, -1151.974]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle123_Metal_0.geometry} material={materials.Metal} position={[1314.045, 758.638, -1151.974]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle124_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[1311.879, 758.638, -1151.974]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle125_Metal_0.geometry} material={materials.Metal} position={[1314.045, 458.613, -1151.974]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle126_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[1311.879, 458.613, -1151.974]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle127_Metal_0.geometry} material={materials.Metal} position={[1314.045, 159.435, -1151.974]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle128_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[1311.879, 159.435, -1151.974]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle129_Metal_0.geometry} material={materials.Metal} position={[1314.045, 2256.341, -614.41]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle130_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[1311.879, 2256.341, -614.41]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle131_Metal_0.geometry} material={materials.Metal} position={[1314.045, 1958.82, -614.41]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle132_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[1311.879, 1958.82, -614.41]} rotation={[-Math.PI, -1.571, 0]} scale={-1} >
        <Html  wrapperClass='laptop' transform occlude center  distanceFactor={0.1} position={[-0.0269,0.287,0.045]} rotation-y={3.10}   rotation-x={-0.10} rotation-z={-0.06}  >
<div  className="iframe">
<About/>
</div>
</Html>
          </mesh>
        <mesh geometry={nodes.Rectangle133_Metal_0.geometry} material={materials.Metal} position={[1314.045, 1656.472, -614.41]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle134_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[1311.879, 1656.472, -614.41]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle135_Metal_0.geometry} material={materials.Metal} position={[1314.045, 1357.274, -614.41]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle136_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[1311.879, 1357.274, -614.41]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle137_Metal_0.geometry} material={materials.Metal} position={[1314.045, 1061.153, -614.41]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle138_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[1311.879, 1061.153, -614.41]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle139_Metal_0.geometry} material={materials.Metal} position={[1314.045, 758.638, -614.41]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle140_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[1311.879, 758.638, -614.41]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle141_Metal_0.geometry} material={materials.Metal} position={[1314.045, 458.613, -614.41]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle142_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[1311.879, 458.613, -614.41]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle143_Metal_0.geometry} material={materials.Metal} position={[1314.045, 159.435, -614.41]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle144_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[1311.879, 159.435, -614.41]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle145_Metal_0.geometry} material={materials.Metal} position={[829.358, 2256.341, 222.445]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle146_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 2256.341, 222.445]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle147_Metal_0.geometry} material={materials.Metal} position={[829.358, 1958.82, 222.445]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle148_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 1958.82, 222.445]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle149_Metal_0.geometry} material={materials.Metal} position={[829.358, 1656.472, 222.445]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle150_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 1656.472, 222.445]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle151_Metal_0.geometry} material={materials.Metal} position={[829.358, 1357.274, 222.445]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle152_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 1357.274, 222.445]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle153_Metal_0.geometry} material={materials.Metal} position={[829.358, 1061.153, 222.445]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle154_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 1061.153, 222.445]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle155_Metal_0.geometry} material={materials.Metal} position={[829.358, 758.638, 222.445]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle156_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 758.638, 222.445]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle157_Metal_0.geometry} material={materials.Metal} position={[829.358, 458.613, 222.445]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle158_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 458.613, 222.445]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle159_Metal_0.geometry} material={materials.Metal} position={[829.358, 159.435, 222.445]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle160_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 159.435, 222.445]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle161_Metal_0.geometry} material={materials.Metal} position={[829.358, 2256.341, 530.462]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle162_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 2256.341, 530.462]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle163_Metal_0.geometry} material={materials.Metal} position={[829.358, 1958.82, 530.462]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle164_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 1958.82, 530.462]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle165_Metal_0.geometry} material={materials.Metal} position={[829.358, 1656.472, 530.462]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle166_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 1656.472, 530.462]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle167_Metal_0.geometry} material={materials.Metal} position={[829.358, 1357.274, 530.462]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle168_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 1357.274, 530.462]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle169_Metal_0.geometry} material={materials.Metal} position={[829.358, 1061.153, 530.462]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle170_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 1061.153, 530.462]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle171_Metal_0.geometry} material={materials.Metal} position={[829.358, 758.638, 530.462]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle172_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 758.638, 530.462]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle173_Metal_0.geometry} material={materials.Metal} position={[829.358, 458.613, 530.462]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle174_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 458.613, 530.462]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle175_Metal_0.geometry} material={materials.Metal} position={[829.358, 159.435, 530.462]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle176_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 159.435, 530.462]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle177_Metal_0.geometry} material={materials.Metal} position={[829.358, 2256.341, 838.226]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle178_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 2256.341, 838.226]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle179_Metal_0.geometry} material={materials.Metal} position={[829.358, 1958.82, 838.226]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle180_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 1958.82, 838.226]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle181_Metal_0.geometry} material={materials.Metal} position={[829.358, 1656.472, 838.226]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle182_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 1656.472, 838.226]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle183_Metal_0.geometry} material={materials.Metal} position={[829.358, 1357.274, 838.226]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle184_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 1357.274, 838.226]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle185_Metal_0.geometry} material={materials.Metal} position={[829.358, 1061.153, 838.226]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle186_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 1061.153, 838.226]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle187_Metal_0.geometry} material={materials.Metal} position={[829.358, 758.638, 838.226]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle188_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 758.638, 838.226]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle189_Metal_0.geometry} material={materials.Metal} position={[829.358, 458.613, 838.226]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle190_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 458.613, 838.226]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle191_Metal_0.geometry} material={materials.Metal} position={[829.358, 159.435, 838.226]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle192_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 159.435, 838.226]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle193_Metal_0.geometry} material={materials.Metal} position={[829.358, 2256.341, 943.245]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle194_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 2256.341, 943.245]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle195_Metal_0.geometry} material={materials.Metal} position={[829.358, 1958.82, 943.245]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle196_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 1958.82, 943.245]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle197_Metal_0.geometry} material={materials.Metal} position={[829.358, 1656.472, 943.245]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle198_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 1656.472, 943.245]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle199_Metal_0.geometry} material={materials.Metal} position={[829.358, 1357.274, 943.245]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle200_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 1357.274, 943.245]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle201_Metal_0.geometry} material={materials.Metal} position={[829.358, 1061.153, 943.245]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle202_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 1061.153, 943.245]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle203_Metal_0.geometry} material={materials.Metal} position={[829.358, 758.638, 943.245]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle204_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 758.638, 943.245]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle205_Metal_0.geometry} material={materials.Metal} position={[829.358, 458.613, 943.245]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle206_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 458.613, 943.245]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle207_Metal_0.geometry} material={materials.Metal} position={[829.358, 159.435, 943.245]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle208_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[827.192, 159.435, 943.245]} rotation={[-Math.PI, -1.571, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle209_Metal_0.geometry} material={materials.Metal} position={[855.185, 2256.341, 1179.718]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle210_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[855.185, 2256.341, 1177.552]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle225_Metal_0.geometry} material={materials.Metal} position={[360.195, 2256.341, 1179.718]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle226_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[360.195, 2256.341, 1177.552]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle241_Metal_0.geometry} material={materials.Metal} position={[1093.084, 2256.341, -102.37]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle242_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[1093.084, 2256.341, -104.536]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle243_Metal_0.geometry} material={materials.Metal} position={[1093.084, 1958.82, -102.37]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle244_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[1093.084, 1958.82, -104.536]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle245_Metal_0.geometry} material={materials.Metal} position={[1093.084, 1656.472, -102.37]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle246_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[1093.084, 1656.472, -104.536]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle247_Metal_0.geometry} material={materials.Metal} position={[1093.084, 1357.274, -102.37]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle248_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[1093.084, 1357.274, -104.536]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle249_Metal_0.geometry} material={materials.Metal} position={[1093.084, 1061.153, -102.37]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle250_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[1093.084, 1061.153, -104.536]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle251_Metal_0.geometry} material={materials.Metal} position={[1093.084, 758.638, -102.37]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle252_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[1093.084, 758.638, -104.536]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle253_Metal_0.geometry} material={materials.Metal} position={[1093.084, 458.613, -102.37]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle254_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[1093.084, 458.613, -104.536]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        <mesh geometry={nodes.Rectangle255_Metal_0.geometry} material={materials.Metal} position={[1093.084, 159.435, -102.37]} rotation={[-Math.PI, 0, 0]} scale={-1} />
        <mesh geometry={nodes['Rectangle256_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[1093.084, 159.435, -104.536]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      </group>
    </group>
  )
}

useGLTF.preload('/untitled.glb')
